# Generated by Django 3.0.5 on 2024-08-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.PositiveIntegerField()),
                ('cutting_type', models.CharField(choices=[('slice', 'Slice'), ('cube', 'Cube'), ('rectangle', 'Rectangle')], max_length=20)),
                ('category', models.CharField(choices=[('domestic', 'Domestic'), ('commercial', 'Commercial')], max_length=10)),
            ],
        ),
    ]
