# Generated by Django 3.0.5 on 2024-08-02 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0002_auto_20240802_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable',
            name='cutting_type',
        ),
    ]
